from PySide6.QtCore import (QCoreApplication, QMetaObject,QRect)
from PySide6.QtGui import (QFont)
from PySide6.QtWidgets import (QFrame, QLabel, QLineEdit,QPushButton)


class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(819, 496)
        self.accountinf = QFrame(Form)
        self.accountinf.setObjectName(u"accountinf")
        self.accountinf.setGeometry(QRect(10, 30, 791, 161))
        self.accountinf.setFrameShape(QFrame.Shape.StyledPanel)
        self.accountinf.setFrameShadow(QFrame.Shadow.Raised)
        self.cadi = QLineEdit(self.accountinf)
        self.cadi.setObjectName(u"cadi")
        self.cadi.setGeometry(QRect(80, 50, 231, 22))
        self.csektor = QLineEdit(self.accountinf)
        self.csektor.setObjectName(u"csektor")
        self.csektor.setGeometry(QRect(80, 90, 231, 22))
        self.ckodu_label = QLabel(self.accountinf)
        self.ckodu_label.setObjectName(u"ckodu_label")
        self.ckodu_label.setGeometry(QRect(10, 11, 61, 16))
        self.cadi_label = QLabel(self.accountinf)
        self.cadi_label.setObjectName(u"cadi_label")
        self.cadi_label.setGeometry(QRect(10, 50, 49, 16))
        self.csektor_label = QLabel(self.accountinf)
        self.csektor_label.setObjectName(u"csektor_label")
        self.csektor_label.setGeometry(QRect(10, 90, 49, 16))
        self.dc_label = QLabel(self.accountinf)
        self.dc_label.setObjectName(u"dc_label")
        self.dc_label.setGeometry(QRect(10, 130, 61, 16))
        self.doviz = QLineEdit(self.accountinf)
        self.doviz.setObjectName(u"doviz")
        self.doviz.setGeometry(QRect(80, 130, 71, 22))
        self.isatis_label = QLabel(self.accountinf)
        self.isatis_label.setObjectName(u"isatis_label")
        self.isatis_label.setGeometry(QRect(450, 50, 49, 16))
        self.satisUzm = QLineEdit(self.accountinf)
        self.satisUzm.setObjectName(u"satisUzm")
        self.satisUzm.setGeometry(QRect(520, 11, 231, 22))
        self.satisYrd = QLineEdit(self.accountinf)
        self.satisYrd.setObjectName(u"satisYrd")
        self.satisYrd.setGeometry(QRect(520, 50, 231, 22))
        self.asatis_label = QLabel(self.accountinf)
        self.asatis_label.setObjectName(u"asatis_label")
        self.asatis_label.setGeometry(QRect(450, 11, 61, 16))
        self.vade_label = QLabel(self.accountinf)
        self.vade_label.setObjectName(u"vade_label")
        self.vade_label.setGeometry(QRect(180, 130, 51, 20))
        self.vade = QLineEdit(self.accountinf)
        self.vade.setObjectName(u"vade")
        self.vade.setGeometry(QRect(240, 130, 71, 22))
        self.satinalma = QLineEdit(self.accountinf)
        self.satinalma.setObjectName(u"satinalma")
        self.satinalma.setGeometry(QRect(520, 90, 231, 22))
        self.email = QLineEdit(self.accountinf)
        self.email.setObjectName(u"email_line")
        self.email.setGeometry(QRect(520, 129, 231, 22))
        self.email_label = QLabel(self.accountinf)
        self.email_label.setObjectName(u"email_label")
        self.email_label.setGeometry(QRect(450, 129, 49, 16))
        self.satinalma_label = QLabel(self.accountinf)
        self.satinalma_label.setObjectName(u"satinalma_label")
        self.satinalma_label.setGeometry(QRect(450, 90, 61, 16))
        self.ckodu = QLineEdit(self.accountinf)
        self.ckodu.setObjectName(u"ckodu")
        self.ckodu.setGeometry(QRect(80, 10, 231, 22))
        self.address = QFrame(Form)
        self.address.setObjectName(u"address")
        self.address.setGeometry(QRect(10, 220, 791, 261))
        self.address.setFrameShape(QFrame.Shape.StyledPanel)
        self.address.setFrameShadow(QFrame.Shadow.Raised)
        self.addr = QLineEdit(self.address)
        self.addr.setObjectName(u"addr")
        self.addr.setGeometry(QRect(80, 11, 671, 22))
        self.addr_label = QLabel(self.address)
        self.addr_label.setObjectName(u"addr_label")
        self.addr_label.setGeometry(QRect(10, 13, 61, 16))
        self.ulke = QLineEdit(self.address)
        self.ulke.setObjectName(u"ulke")
        self.ulke.setGeometry(QRect(80, 50, 161, 22))
        self.ulke_label = QLabel(self.address)
        self.ulke_label.setObjectName(u"ulke_label")
        self.ulke_label.setGeometry(QRect(10, 52, 61, 16))
        self.il_label = QLabel(self.address)
        self.il_label.setObjectName(u"il_label")
        self.il_label.setGeometry(QRect(265, 52, 61, 16))
        self.il = QLineEdit(self.address)
        self.il.setObjectName(u"il")
        self.il.setGeometry(QRect(335, 50, 161, 22))
        self.ile_label = QLabel(self.address)
        self.ile_label.setObjectName(u"ile_label")
        self.ile_label.setGeometry(QRect(520, 52, 61, 16))
        self.ilce = QLineEdit(self.address)
        self.ilce.setObjectName(u"ilce")
        self.ilce.setGeometry(QRect(590, 50, 161, 22))
        self.mmail_label = QLabel(self.address)
        self.mmail_label.setObjectName(u"mmail_label")
        self.mmail_label.setGeometry(QRect(10, 90, 61, 16))
        self.mmail = QLineEdit(self.address)
        self.mmail.setObjectName(u"mmail")
        self.mmail.setGeometry(QRect(80, 90, 231, 22))
        self.mobil = QLineEdit(self.address)
        self.mobil.setObjectName(u"mobil")
        self.mobil.setGeometry(QRect(80, 170, 231, 22))
        self.mobil_label = QLabel(self.address)
        self.mobil_label.setObjectName(u"mobil_label")
        self.mobil_label.setGeometry(QRect(10, 170, 61, 16))
        self.tel = QLineEdit(self.address)
        self.tel.setObjectName(u"tel")
        self.tel.setGeometry(QRect(80, 130, 231, 22))
        self.tel_label = QLabel(self.address)
        self.tel_label.setObjectName(u"tel_label")
        self.tel_label.setGeometry(QRect(10, 130, 61, 16))
        self.fax_label = QLabel(self.address)
        self.fax_label.setObjectName(u"fax_label")
        self.fax_label.setGeometry(QRect(10, 210, 61, 16))
        self.fax = QLineEdit(self.address)
        self.fax.setObjectName(u"fax")
        self.fax.setGeometry(QRect(80, 210, 231, 22))
        self.iban_label = QLabel(self.address)
        self.iban_label.setObjectName(u"iban_label")
        self.iban_label.setGeometry(QRect(340, 210, 61, 16))
        self.vno = QLineEdit(self.address)
        self.vno.setObjectName(u"vno")
        self.vno.setGeometry(QRect(420, 130, 331, 22))
        self.bank_label = QLabel(self.address)
        self.bank_label.setObjectName(u"bank_label")
        self.bank_label.setGeometry(QRect(340, 170, 61, 16))
        self.iban = QLineEdit(self.address)
        self.iban.setObjectName(u"iban")
        self.iban.setGeometry(QRect(420, 210, 331, 22))
        self.vno_label = QLabel(self.address)
        self.vno_label.setObjectName(u"vno_label")
        self.vno_label.setGeometry(QRect(340, 130, 61, 16))
        self.vd = QLineEdit(self.address)
        self.vd.setObjectName(u"vd")
        self.vd.setGeometry(QRect(420, 90, 331, 22))
        self.bank = QLineEdit(self.address)
        self.bank.setObjectName(u"bank")
        self.bank.setGeometry(QRect(420, 170, 331, 22))
        self.vd_label = QLabel(self.address)
        self.vd_label.setObjectName(u"vd_label")
        self.vd_label.setGeometry(QRect(340, 90, 71, 16))
        self.label = QLabel(Form)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 196, 111, 20))
        font = QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setUnderline(True)
        self.label.setFont(font)
        self.label_2 = QLabel(Form)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 10, 111, 16))
        font1 = QFont()
        font1.setPointSize(11)
        font1.setUnderline(True)
        self.label_2.setFont(font1)
        self.regButton = QPushButton(Form)
        self.regButton.setObjectName(u"regButton")
        self.regButton.setGeometry(QRect(625, 6, 75, 24))
        self.exitButton = QPushButton(Form)
        self.exitButton.setObjectName(u"regButton")
        self.exitButton.setGeometry(QRect(710, 6, 75, 24))

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.ckodu_label.setText(QCoreApplication.translate("Form", u"Cari Kodu", None))
        self.cadi_label.setText(QCoreApplication.translate("Form", u"Cari Adı", None))
        self.csektor_label.setText(QCoreApplication.translate("Form", u"Sektörü", None))
        self.dc_label.setText(QCoreApplication.translate("Form", u"Döviz Cinsi", None))
        self.isatis_label.setText(QCoreApplication.translate("Form", u"iç Satış", None))
        self.asatis_label.setText(QCoreApplication.translate("Form", u"Alan Satış", None))
        self.vade_label.setText(QCoreApplication.translate("Form", u"Vade", None))
        self.vade.setText("")
        self.email_label.setText(QCoreApplication.translate("Form", u"E-Posta", None))
        self.satinalma_label.setText(QCoreApplication.translate("Form", u"Satınalma", None))
        self.addr_label.setText(QCoreApplication.translate("Form", u"Adres", None))
        self.ulke_label.setText(QCoreApplication.translate("Form", u"Ülke", None))
        self.il_label.setText(QCoreApplication.translate("Form", u"il", None))
        self.ile_label.setText(QCoreApplication.translate("Form", u"ilçe", None))
        self.mmail_label.setText(QCoreApplication.translate("Form", u"Muh. Mail", None))
        self.mobil_label.setText(QCoreApplication.translate("Form", u"Mobil", None))
        self.tel_label.setText(QCoreApplication.translate("Form", u"Telefon", None))
        self.fax_label.setText(QCoreApplication.translate("Form", u"Fax", None))
        self.iban_label.setText(QCoreApplication.translate("Form", u"IBAN No", None))
        self.bank_label.setText(QCoreApplication.translate("Form", u"Banka Adı", None))
        self.vno_label.setText(QCoreApplication.translate("Form", u"Vergi No", None))
        self.vd_label.setText(QCoreApplication.translate("Form", u"Vergi Dairesi", None))
        self.label.setText(QCoreApplication.translate("Form", u"iletişim Bilgisi", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"Cari Bilgisi", None))
        self.regButton.setText(QCoreApplication.translate("Form", u"Kayıt", None))
        self.exitButton.setText(QCoreApplication.translate("Form", u"Çıkış", None))
    # retranslateUi