from PySide6.QtCore import (QCoreApplication, QMetaObject, QRect, QSize, Qt)
from PySide6.QtGui import (QAction, QIcon)
from PySide6.QtWidgets import (QCalendarWidget, QLabel, QMenu, QMenuBar, QPushButton, QStatusBar, QWidget)

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        if not mainWindow.objectName():
            mainWindow.setObjectName(u"mainWindow")
        mainWindow.resize(800, 500)
        mainWindow.setToolButtonStyle(Qt.ToolButtonStyle.ToolButtonIconOnly)
        self.action_k = QAction(mainWindow)
        self.action_k.setObjectName(u"action_k")
        self.cikis = QAction(mainWindow)
        self.cikis.setObjectName(u"cikis")
        icon = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.ApplicationExit))
        self.cikis.setIcon(icon)
        self.centralwidget = QWidget(mainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.calendar = QCalendarWidget(self.centralwidget)
        self.calendar.setObjectName(u"calendar")
        self.calendar.setGeometry(QRect(520, 10, 264, 190))
        self.cariRegister = QPushButton(self.centralwidget)
        self.cariRegister.setObjectName(u"cariRegister")
        self.cariRegister.setGeometry(QRect(30, 40, 75, 75))
        icon1 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.ContactNew))
        self.cariRegister.setIcon(icon1)
        self.cariRegister.setIconSize(QSize(25, 25))
        self.cariRegLabel = QLabel(self.centralwidget)
        self.cariRegLabel.setObjectName(u"cariRegLabel")
        self.cariRegLabel.setGeometry(QRect(40, 120, 49, 16))
        self.urunRegister = QPushButton(self.centralwidget)
        self.urunRegister.setObjectName(u"urunRegister")
        self.urunRegister.setGeometry(QRect(140, 40, 75, 75))
        icon2 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentNew))
        self.urunRegister.setIcon(icon2)
        self.urunRegister.setIconSize(QSize(25, 25))
        self.urunRegLabel = QLabel(self.centralwidget)
        self.urunRegLabel.setObjectName(u"urunRegLabel")
        self.urunRegLabel.setGeometry(QRect(149, 120, 61, 16))
        self.saModuleLabel = QLabel(self.centralwidget)
        self.saModuleLabel.setObjectName(u"saModuleLabel")
        self.saModuleLabel.setGeometry(QRect(372, 120, 61, 16))
        self.siparisModule = QPushButton(self.centralwidget)
        self.siparisModule.setObjectName(u"siparisModule")
        self.siparisModule.setGeometry(QRect(250, 40, 75, 75))
        icon3 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.FolderNew))
        self.siparisModule.setIcon(icon3)
        self.siparisModule.setIconSize(QSize(25, 25))
        self.siparisLabel = QLabel(self.centralwidget)
        self.siparisLabel.setObjectName(u"siparisLabel")
        self.siparisLabel.setGeometry(QRect(270, 120, 41, 16))
        self.saModule = QPushButton(self.centralwidget)
        self.saModule.setObjectName(u"saModule")
        self.saModule.setGeometry(QRect(360, 40, 75, 75))
        icon4 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.EditSelectAll))
        self.saModule.setIcon(icon4)
        self.saModule.setIconSize(QSize(25, 25))
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QStatusBar(mainWindow)
        self.statusBar.setObjectName(u"statusBar")
        mainWindow.setStatusBar(self.statusBar)
        self.menuBar = QMenuBar(mainWindow)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 800, 33))
        self.menuDosya = QMenu(self.menuBar)
        self.menuDosya.setObjectName(u"menuDosya")
        mainWindow.setMenuBar(self.menuBar)

        self.menuBar.addAction(self.menuDosya.menuAction())
        self.menuDosya.addAction(self.cikis)

        self.retranslateUi(mainWindow)

        QMetaObject.connectSlotsByName(mainWindow)
    # setupUi

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(QCoreApplication.translate("mainWindow", u"MainWindow", None))
        self.action_k.setText(QCoreApplication.translate("mainWindow", u"Çıkış", None))
        self.cikis.setText(QCoreApplication.translate("mainWindow", u"Çıkış", None))
        self.cariRegister.setText("")
        self.cariRegLabel.setText(QCoreApplication.translate("mainWindow", u"Cari Kayıt", None))
        self.urunRegister.setText("")
        self.urunRegLabel.setText(QCoreApplication.translate("mainWindow", u"Ürün Kayıt", None))
        self.saModuleLabel.setText(QCoreApplication.translate("mainWindow", u"Satınalma", None))
        self.siparisModule.setText("")
        self.siparisLabel.setText(QCoreApplication.translate("mainWindow", u"Sipariş", None))
        self.saModule.setText("")
        self.menuDosya.setTitle(QCoreApplication.translate("mainWindow", u"Dosya", None))
    # retranslateUi