from PySide6.QtCore import (QCoreApplication, QMetaObject, QRect)
from PySide6.QtGui import (QFont)
from PySide6.QtWidgets import (QComboBox, QFrame, QLabel, QLineEdit, QPushButton)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.setEnabled(True)
        Form.resize(400, 262)
        self.u_frame = QFrame(Form)
        self.u_frame.setObjectName(u"u_frame")
        self.u_frame.setGeometry(QRect(10, 30, 371, 181))
        self.u_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.u_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.u_kodu_label = QLabel(self.u_frame)
        self.u_kodu_label.setObjectName(u"u_kodu_label")
        self.u_kodu_label.setGeometry(QRect(20, 20, 61, 16))
        self.u_adi_label = QLabel(self.u_frame)
        self.u_adi_label.setObjectName(u"u_adi_label")
        self.u_adi_label.setGeometry(QRect(20, 50, 61, 16))
        self.sub_label = QLabel(self.u_frame)
        self.sub_label.setObjectName(u"sub_label")
        self.sub_label.setGeometry(QRect(20, 110, 71, 16))
        self.categori_label = QLabel(self.u_frame)
        self.categori_label.setObjectName(u"categori_label")
        self.categori_label.setGeometry(QRect(20, 80, 61, 16))
        self.urun_kodu = QLineEdit(self.u_frame)
        self.urun_kodu.setObjectName(u"urun_kodu")
        self.urun_kodu.setGeometry(QRect(100, 15, 241, 22))
        self.urun_adi = QLineEdit(self.u_frame)
        self.urun_adi.setObjectName(u"urun_adi")
        self.urun_adi.setGeometry(QRect(100, 45, 241, 22))
        self.catBox = QComboBox(self.u_frame)
        self.catBox.setObjectName(u"catBox")
        self.catBox.setGeometry(QRect(100, 80, 241, 25))
        self.catBox.setEditable(False)
        self.subBox = QComboBox(self.u_frame)
        self.subBox.setObjectName(u"subBox")
        self.subBox.setGeometry(QRect(100, 110, 241, 25))
        self.subBox.setEditable(False)
        self.durum = QLabel(self.u_frame)
        self.durum.setObjectName(u"durum")
        self.durum.setGeometry(QRect(20, 150, 49, 16))
        self.durumSet = QLabel(self.u_frame)
        self.durumSet.setObjectName(u"durumSet")
        self.durumSet.setGeometry(QRect(80, 150, 261, 16))
        self.label = QLabel(Form)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 4, 81, 21))
        font = QFont()
        font.setPointSize(12)
        font.setUnderline(True)
        self.label.setFont(font)
        self.register = QPushButton(Form, clicked = lambda : self.kayit())
        self.register.setObjectName(u"pushButton")
        self.register.setGeometry(QRect(300, 219, 75, 24))

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

        self.catBox.addItem("Pasifler")
        self.catBox.addItem("Aktifler")
        self.catBox.addItem("Kristaller")
        self.catBox.addItem("Osilatörler")
        
        self.subBox.addItem("Direnç")
        self.subBox.addItem("Diyot")
        self.subBox.addItem("Entegre")
        self.subBox.addItem("Konnektör")
        
        
        
    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.u_kodu_label.setText(QCoreApplication.translate("Form", u"Ürün Kodu", None))
        self.u_adi_label.setText(QCoreApplication.translate("Form", u"Ürün Adı", None))
        self.sub_label.setText(QCoreApplication.translate("Form", u"Alt Kategori", None))
        self.categori_label.setText(QCoreApplication.translate("Form", u"Kategori", None))
        self.durum.setText(QCoreApplication.translate("Form", u"Durum :", None))
        self.durumSet.setText("")
        self.label.setText(QCoreApplication.translate("Form", u"Ürün Kartı", None))
        self.register.setText(QCoreApplication.translate("Form", u"Kayıt", None))
    # retranslateUi